include $(THEOS)/makefiles/common.mk

LIBRARY_NAME = EnterpriseLoader

EnterpriseLoader_FILES = EnterpriseLoader.m
EnterpriseLoader_CFLAGS = -objc-arc
EnterpriseLoader_INSTALL_PATH = /Applications/Geode.app/Frameworks

include $(THEOS_MAKE_PATH)/library.mk
